#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=10

banner "Editing surface bake-off — account setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Scratch repo — name it"
say "Sveltia needs a real GitHub repo with a write collaborator, and GitHub Pages"
say "needs it public on a free plan. Nothing here is the Contractor's own account:"
say "this is a throwaway that gets deleted when the bake-off is over."
note "It holds only his public website copy and 3 photos already on his live site."
ask BAKEOFF_REPO "Repo to create, as owner/name [nikzorz/ctm-bakeoff]:"
[[ -z "$BAKEOFF_REPO" ]] && BAKEOFF_REPO="nikzorz/ctm-bakeoff"
write_env BAKEOFF_REPO "$BAKEOFF_REPO"
export GH_REPO="$BAKEOFF_REPO"   # every gh call below targets the scratch repo

if gh repo view "$BAKEOFF_REPO" >/dev/null 2>&1; then
  note "$BAKEOFF_REPO already exists — reusing it."
elif confirm "Create $BAKEOFF_REPO as a PUBLIC repo now?"; then
  gh repo create "$BAKEOFF_REPO" --public \
    --description "Throwaway: editing surface bake-off for nikzorz/ctm#16"
  say "created."
else
  warn "Skipped. Nothing downstream will work until this repo exists."
  SKIPPED+=("create $BAKEOFF_REPO")
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Scratch repo — push the bake-off into it"
say "The prototype becomes the root of that repo, so the CMSes see content/ at the top."
ask WORKDIR "Where to put the working clone [\$HOME/ctm-bakeoff]:"
[[ -z "$WORKDIR" ]] && WORKDIR="$HOME/ctm-bakeoff"
write_env WORKDIR "$WORKDIR"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -d "$WORKDIR/.git" ]]; then
  note "$WORKDIR is already a clone — leaving it alone."
elif confirm "Copy the prototype to $WORKDIR and push it to $BAKEOFF_REPO?"; then
  mkdir -p "$WORKDIR"
  rsync -a --exclude node_modules --exclude dist --exclude .astro \
        --exclude 'tina/__generated__' --exclude 'public/tina-admin' \
        "$HERE"/ "$WORKDIR"/
  git -C "$WORKDIR" init -q -b main
  git -C "$WORKDIR" add -A
  git -C "$WORKDIR" -c user.email="$(git config user.email)" \
      -c user.name="$(git config user.name)" commit -q -m "Bake-off: one content folder, three editing surfaces"
  git -C "$WORKDIR" remote add origin "https://github.com/$BAKEOFF_REPO.git" 2>/dev/null || true
  git -C "$WORKDIR" push -u origin main
  say "pushed."
else
  SKIPPED+=("push the prototype to $BAKEOFF_REPO")
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "GitHub Pages — turn it on"
say "This is what makes the arms reachable from his phone. Local mode is not enough:"
say "neither CMS authenticates anybody locally, and auth is the axis that decides this."
open_url "https://github.com/$BAKEOFF_REPO/settings/pages"
step "Under 'Build and deployment', set Source to 'GitHub Actions'."
step "Leave everything else alone and come back here."
pause "Done?"
SITE_URL="https://${BAKEOFF_REPO%%/*}.github.io/${BAKEOFF_REPO##*/}"
say "Your site will be: $SITE_URL"
write_env SITE_URL "$SITE_URL"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "TinaCloud — create the project (Arm 2)"
say "Tina means TinaCloud: no self-hosted Tina backend runs on Workers, so this vendor"
say "is not optional, and it is priced PER PROJECT against a template meant for many clients."
open_url "https://app.tina.io/projects/new"
step "Sign in, then create a project from an existing repository."
step "Pick $BAKEOFF_REPO and branch 'main'."
step "When it finishes, open the project's Overview tab."
warn "While you are there, note two things the pricing page does not say:"
note "  - whether it asks for a card, and"
note "  - how many FREE projects one account may hold. Per-project billing with an"
note "    unknown free-project cap is a real risk for a template reused across clients."
note "  - whether creating the project required YOU to authorise GitHub. If it did,"
note "    then Tina's one advantage over Sveltia only holds while WE own the project,"
note "    because his owning it would re-impose the GitHub account Tina removes."
ask TINA_PUBLIC_CLIENT_ID "Paste the Client ID:"
step "Now open the Tokens tab and generate a read-only content token."
ask_secret TINA_TOKEN "Paste the token:"
write_env TINA_PUBLIC_CLIENT_ID "$TINA_PUBLIC_CLIENT_ID"
write_env TINA_TOKEN "$TINA_TOKEN"
set_var TINA_PUBLIC_CLIENT_ID "$TINA_PUBLIC_CLIENT_ID"
set_secret TINA_TOKEN "$TINA_TOKEN"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "TinaCloud — invite the Contractor (skippable)"
say "The free tier is 2 users, hard capped, per project. You plus him fills it exactly,"
say "with zero headroom, for every client. Inviting him IS that test."
note "Skip this if you do not have his details yet; re-run the wizard later."
if confirm "Invite him to the TinaCloud project now?"; then
  open_url "https://app.tina.io/"
  step "Project → Collaborators → Invite, and enter his email."
  step "Watch what the invite email asks him to do. Write it down."
  pause "Done?"
else
  SKIPPED+=("invite the Contractor to TinaCloud (the 2-seat ceiling test)")
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare — deploy the Sveltia auth Worker (Arm 1)"
say "Sveltia has NO hosted auth, by stated vendor policy: 'legal, privacy and security"
say "liabilities that we cannot afford'. So somebody runs this Worker. That is a real,"
say "permanent cost of the Sveltia arm and it belongs in the comparison."
note "Use any Cloudflare account you control. It need not be the Contractor's, and it is"
note "not the account the host ticket provisions."
open_url "https://github.com/sveltia/sveltia-cms-auth"
step "Follow its README to deploy the Worker (Deploy button, or wrangler deploy)."
step "When it is live, copy the Worker's URL."
ask SVELTIA_AUTH_URL "Paste the Worker URL (no trailing slash):"
SVELTIA_AUTH_URL="${SVELTIA_AUTH_URL%/}"
write_env SVELTIA_AUTH_URL "$SVELTIA_AUTH_URL"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "GitHub — OAuth App for Sveltia"
say "The callback has to point at the Worker you just deployed, which is why this"
say "stage comes second."
open_url "https://github.com/settings/applications/new"
step "Application name: CTM bake-off (Sveltia)"
step "Homepage URL:     $SITE_URL"
step "Callback URL:     $SVELTIA_AUTH_URL/callback"
step "Register, then copy the Client ID, then 'Generate a new client secret'."
ask GH_OAUTH_CLIENT_ID "Paste the OAuth Client ID:"
ask_secret GH_OAUTH_CLIENT_SECRET "Paste the OAuth Client Secret:"
write_env GH_OAUTH_CLIENT_ID "$GH_OAUTH_CLIENT_ID"
write_env GH_OAUTH_CLIENT_SECRET "$GH_OAUTH_CLIENT_SECRET"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare — put those secrets on the Worker"
say "ALLOWED_DOMAINS is not optional in spirit: without it, any other site can drive your"
say "Worker at your expense and mint tokens through it."
say "Run these in your sveltia-cms-auth checkout:"
note "  npx wrangler secret put GITHUB_CLIENT_ID       # $GH_OAUTH_CLIENT_ID"
note "  npx wrangler secret put GITHUB_CLIENT_SECRET   # the one you just pasted"
note "  npx wrangler secret put ALLOWED_DOMAINS        # ${BAKEOFF_REPO%%/*}.github.io"
pause "Done?"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Point Sveltia's config at the real repo and Worker"
CFG="${WORKDIR:-$HOME/ctm-bakeoff}/public/admin/config.yml"
if [[ -f "$CFG" ]]; then
  sed -i.bak "s|SVELTIA_REPO_PLACEHOLDER|$BAKEOFF_REPO|; s|SVELTIA_AUTH_URL_PLACEHOLDER|$SVELTIA_AUTH_URL|" "$CFG"
  rm -f "$CFG.bak"
  say "patched $CFG"
  git -C "${WORKDIR:-$HOME/ctm-bakeoff}" add public/admin/config.yml
  git -C "${WORKDIR:-$HOME/ctm-bakeoff}" -c user.email="$(git config user.email)" \
      -c user.name="$(git config user.name)" commit -q -m "Point Sveltia at the scratch repo and auth Worker" || true
  git -C "${WORKDIR:-$HOME/ctm-bakeoff}" push -q origin main || warn "push failed; push by hand"
  say "pushed. Pages will rebuild."
else
  warn "config.yml not found at $CFG — patch repo and base_url by hand."
  SKIPPED+=("patch public/admin/config.yml")
fi

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Invite the Contractor to the repo (skippable)"
say "Sveltia requires WRITE permission, not read: the editor commits as him."
say "Arm 3 needs the same account. If this fails, arms 1 and 3 fail together and Tina"
say "wins by default, so this is the single most load-bearing step in the whole bake-off."
if confirm "Invite him as a collaborator now?"; then
  ask CONTRACTOR_GITHUB_USER "His GitHub username:"
  write_env CONTRACTOR_GITHUB_USER "$CONTRACTOR_GITHUB_USER"
  gh api -X PUT "repos/$BAKEOFF_REPO/collaborators/$CONTRACTOR_GITHUB_USER" \
    -f permission=push >/dev/null && say "invited with write permission."
  step "Have him accept the invite, and watch how long that takes and what he asks."
  pause "Done?"
else
  SKIPPED+=("invite the Contractor to $BAKEOFF_REPO with write permission")
fi

say ""
say "Now open TASKS.md and run the session. The three arms are:"
note "  Arm 1  $SITE_URL/admin/       Sveltia"
note "  Arm 2  $SITE_URL/tina-admin/  Tina"
note "  Arm 3  $SITE_URL/upload/      no CMS, plus an agent in the repo"

finish
